repos:
-   repo: https://github.com/python-telegram-bot/mirrors-yapf
    rev: v0.12.2
    hooks:
    -   id: yapf
        files: ^(ptbtest|tests)/.*\.py$
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 414cfa7b2322cf1c46cd33a49e9da833ad785473
    hooks:
    -   id: flake8
        files: ^ptbtest/.*\.py$
        args:
        - --max-line-length=120
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
    -   id: pylint
        files: ^ptbtest/.*\.py$
        args:
        - --errors-only
        - --disable=no-name-in-module,import-error
